### ISSUE TITLE
Got the error "Failed to receive 1 resource signal(s) within the specified duration" when creating the instance

### ISSUE THREAD

**Issue by eric80116** [terrificdm/stable-diffusion-ec2#1]
The cloudformation created the instance successfully but did not continuously processing and failed after 1 hour with "Failed to receive 1 resource signal(s) within the specified duration" error message? Do I need to configure any parameter except the key-pair name?

**Comment by terrificdm** [comment]
No, just key pair. Which region were u deploying the stack? The error related with webui dependences installation, if all packages are not installed within 60m, then fail signal will pop up. So might be network latency issue or something...

You can remote access the instance through key pair as long as instance is up, and tail -f sd-webui.log to check what's going on with installation.

Also, you can modify the max time for dependences installation above 60m if you want... https://github.com/terrificdm/stable-diffusion-ec2/blob/main/lib/stable-diffusion-ec2-stack.ts#L52

**Comment by eric80116** [comment]
I found my ec2 instance be started at private subnet and cannot get the nvidia package from internet. After changing the routing table to connect igw manually then it works. Thanks
